apiVersion: v1
kind: ConfigMap
metadata:
  name: "consul-test-config"
data:
  server.json: |
    {
      "raft_protocol": 3,
      "autopilot": {
        "last_contact_threshold": "200ms",
        "max_trailing_logs": 250,
        "server_stabilization_time": "10s"
      }
    }
