apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-util
spec:
  replicas: 9
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
         - containerPort: 80
